add:
	gcc -Wall -o ./add_test ./unittest/add_test.c ../mulprec.c ../utils.c -lm

sub:
	gcc -Wall -o ./sub_test ./unittest/sub_test.c ../mulprec.c ../utils.c -lm

multiple:
	gcc -Wall -o ./multiple_test ./unittest/multiple_test.c ../mulprec.c ../utils.c -lm

divide:
	gcc -Wall -o ./divide_test ./unittest/divide_test.c ../mulprec.c ../utils.c -lm

